USE ecommerce_data;

-- Basic Queries

-- Q1. Show all customers, newest signups first
SELECT
    customer_id,
    CONCAT(first_name, ' ', last_name) AS full_name,
    signup_date
FROM customers
ORDER BY signup_date DESC;


-- Q2. All orders that were delivered in 2023
SELECT
    order_id,
    customer_id,
    order_date,
    shipped_date,
    status
FROM orders
WHERE status = 'Delivered'
  AND order_date BETWEEN '2023-01-01' AND '2023-12-31'
ORDER BY order_date;


-- Q3. Products priced between 5,000 and 20,000 (cheapest first)
SELECT
    product_name,
    unit_price,
    stock_qty
FROM products
WHERE unit_price BETWEEN 5000 AND 20000
ORDER BY unit_price ASC;


-- Q4. Customers living in Karachi or Lahore
SELECT
    CONCAT(first_name, ' ', last_name) AS full_name,
    city,
    email
FROM customers
WHERE city IN ('Karachi', 'Lahore');


-- Q5. Orders that haven't been shipped yet
SELECT
    order_id,
    customer_id,
    order_date,
    status
FROM orders
WHERE shipped_date IS NULL;


-- Q6. Calculate the revenue for each line item in an order
SELECT
    order_id,
    product_id,
    quantity,
    unit_price,
    discount_pct,
    ROUND(quantity * unit_price * (1 - discount_pct), 2) AS line_revenue
FROM order_items
ORDER BY order_id;


-- Q7. Find all products that have "Set" in their name
SELECT
    product_name,
    unit_price,
    stock_qty
FROM products
WHERE product_name LIKE '%Set%';


-- Q8. The 5 most expensive products we sell
SELECT
    product_name,
    unit_price
FROM products
ORDER BY unit_price DESC
LIMIT 5;


-- SECTION 4: Aggregation and Grouping

-- Q9. How many customers do we have in each segment?
SELECT
    segment,
    COUNT(*) AS total_customers
FROM customers
GROUP BY segment
ORDER BY total_customers DESC;


-- Q10. Total revenue generated by each order
SELECT
    oi.order_id,
    ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS order_revenue
FROM order_items oi
GROUP BY oi.order_id
ORDER BY order_revenue DESC;


-- Q11. Price stats for each product category
-- Shows average, lowest, and highest price per category
SELECT
    c.category_name,
    COUNT(p.product_id)          AS total_products,
    ROUND(AVG(p.unit_price), 2)  AS avg_price,
    MIN(p.unit_price)            AS min_price,
    MAX(p.unit_price)            AS max_price
FROM products p
JOIN categories c ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY avg_price DESC;


-- Q12. Which months had revenue above 100,000?
SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS order_month,
    ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS monthly_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.status != 'Cancelled'
GROUP BY order_month
HAVING monthly_revenue > 100000
ORDER BY order_month;


-- Q13. How many orders has each employee handled?
SELECT
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name) AS employee_name,
    COUNT(o.order_id) AS orders_handled
FROM employees e
LEFT JOIN orders o ON e.employee_id = o.employee_id
GROUP BY e.employee_id, employee_name
ORDER BY orders_handled DESC;


-- SECTION 5: Joins

-- Q14. Every order with the customer name and the employee who handled it
SELECT
    o.order_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.city,
    CONCAT(e.first_name, ' ', e.last_name) AS handled_by,
    o.order_date,
    o.status
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
INNER JOIN employees e ON o.employee_id = e.employee_id
ORDER BY o.order_date;


-- Q15. All customers and how many orders each one has placed
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.segment,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, customer_name, c.segment
ORDER BY total_orders DESC;


-- Q16. Customers who have never placed a single order
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.email,
    c.signup_date
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- Q17. Each employee paired with their manager's name
SELECT
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name) AS employee_name,
    e.job_title,
    CONCAT(m.first_name, ' ', m.last_name) AS manager_name
FROM employees e
LEFT JOIN employees m ON e.manager_id = m.employee_id
ORDER BY m.employee_id;


-- Q18. Full order breakdown: customer, product, category, and line total
SELECT
    o.order_id,
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer,
    p.product_name,
    cat.category_name,
    oi.quantity,
    oi.unit_price,
    oi.discount_pct,
    ROUND(oi.quantity * oi.unit_price * (1 - oi.discount_pct), 2) AS line_total
FROM orders o
JOIN customers   cu  ON o.customer_id = cu.customer_id
JOIN order_items oi  ON o.order_id    = oi.order_id
JOIN products    p   ON oi.product_id = p.product_id
JOIN categories  cat ON p.category_id = cat.category_id
ORDER BY o.order_id;



-- SECTION 6: Subqueries and CASE WHEN

-- Q19. Customers who have spent more than the average order value
SELECT
    cu.customer_id,
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
    ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS total_spent
FROM customers cu
JOIN orders      o  ON cu.customer_id = o.customer_id
JOIN order_items oi ON o.order_id     = oi.order_id
WHERE o.status != 'Cancelled'
GROUP BY cu.customer_id, customer_name
HAVING total_spent > (
    SELECT AVG(order_total)
    FROM (
        SELECT SUM(quantity * unit_price * (1 - discount_pct)) AS order_total
        FROM order_items
        GROUP BY order_id
    ) AS sub
)
ORDER BY total_spent DESC;


-- Q20. Products that have been ordered at least once
SELECT
    product_id,
    product_name,
    unit_price
FROM products
WHERE product_id IN (
    SELECT DISTINCT product_id FROM order_items
);


-- Q21. Products that have never been ordered at all
SELECT
    product_id,
    product_name,
    unit_price
FROM products
WHERE product_id NOT IN (
    SELECT DISTINCT product_id FROM order_items
);


-- Q22. Assign each customer a value tier based on how much they've spent
-- Tiers go from Bronze (lowest) up to Platinum (highest)
SELECT
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
    ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS total_spent,
    CASE
        WHEN SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)) >= 200000 THEN 'Platinum'
        WHEN SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)) >= 100000 THEN 'Gold'
        WHEN SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)) >= 30000  THEN 'Silver'
        ELSE 'Bronze'
    END AS value_tier
FROM customers cu
JOIN orders      o  ON cu.customer_id = o.customer_id
JOIN order_items oi ON o.order_id     = oi.order_id
WHERE o.status != 'Cancelled'
GROUP BY cu.customer_id, customer_name
ORDER BY total_spent DESC;


-- Q23. For each employee, count how many orders ended up in each status
SELECT
    CONCAT(e.first_name, ' ', e.last_name) AS employee_name,
    COUNT(o.order_id)                                          AS total_orders,
    SUM(CASE WHEN o.status = 'Delivered'  THEN 1 ELSE 0 END)  AS delivered,
    SUM(CASE WHEN o.status = 'Cancelled'  THEN 1 ELSE 0 END)  AS cancelled,
    SUM(CASE WHEN o.status = 'Processing' THEN 1 ELSE 0 END)  AS processing,
    SUM(CASE WHEN o.status = 'Pending'    THEN 1 ELSE 0 END)  AS pending
FROM employees e
LEFT JOIN orders o ON e.employee_id = o.employee_id
GROUP BY e.employee_id, employee_name
ORDER BY total_orders DESC;


-- Q24. Products that cost more than the average price in their own category
SELECT
    p.product_name,
    p.unit_price,
    c.category_name,
    ROUND((
        SELECT AVG(p2.unit_price)
        FROM products p2
        WHERE p2.category_id = p.category_id
    ), 2) AS category_avg_price
FROM products p
JOIN categories c ON p.category_id = c.category_id
WHERE p.unit_price > (
    SELECT AVG(p3.unit_price)
    FROM products p3
    WHERE p3.category_id = p.category_id
)
ORDER BY c.category_name, p.unit_price DESC;


-- SECTION 7: Views


-- View 1: A reusable summary of every order with customer, employee, region, and revenue
-- We use this view in window function and CTE queries below
CREATE OR REPLACE VIEW vw_order_summary AS
SELECT
    o.order_id,
    o.order_date,
    o.status,
    cu.customer_id,
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
    cu.segment,
    cu.city,
    CONCAT(e.first_name, ' ', e.last_name)   AS employee_name,
    r.region_name,
    ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS order_revenue
FROM orders o
JOIN customers      cu ON o.customer_id  = cu.customer_id
JOIN order_items    oi ON o.order_id     = oi.order_id
LEFT JOIN employees  e ON o.employee_id  = e.employee_id
LEFT JOIN sales_regions r ON e.region_id = r.region_id
GROUP BY
    o.order_id, o.order_date, o.status,
    cu.customer_id, customer_name, cu.segment, cu.city,
    employee_name, r.region_name;


-- View 2: How each product is performing in terms of units sold and total revenue
CREATE OR REPLACE VIEW vw_product_performance AS
SELECT
    p.product_id,
    p.product_name,
    c.category_name,
    p.unit_price,
    p.stock_qty,
    COALESCE(SUM(oi.quantity), 0)                                             AS total_units_sold,
    COALESCE(ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2), 0) AS total_revenue
FROM products p
JOIN categories  c  ON p.category_id  = c.category_id
LEFT JOIN order_items oi ON p.product_id = oi.product_id
LEFT JOIN orders       o ON oi.order_id  = o.order_id AND o.status != 'Cancelled'
GROUP BY p.product_id, p.product_name, c.category_name, p.unit_price, p.stock_qty;


-- Quick test: use both views
SELECT * FROM vw_order_summary      WHERE status = 'Delivered' ORDER BY order_revenue DESC;
SELECT * FROM vw_product_performance ORDER BY total_revenue DESC;



-- SECTION 8: Window Functions

-- Q25. Number each customer within their city, ordered by signup date
-- ROW_NUMBER restarts from 1 for every new city
SELECT
    ROW_NUMBER() OVER (PARTITION BY city ORDER BY signup_date) AS row_num,
    customer_id,
    CONCAT(first_name, ' ', last_name) AS customer_name,
    city,
    signup_date
FROM customers;


-- Q26. Rank products by revenue within each category
-- RANK skips numbers after a tie, DENSE_RANK does not
SELECT
    category_name,
    product_name,
    total_revenue,
    RANK()       OVER (PARTITION BY category_name ORDER BY total_revenue DESC) AS revenue_rank,
    DENSE_RANK() OVER (PARTITION BY category_name ORDER BY total_revenue DESC) AS dense_rnk
FROM vw_product_performance
ORDER BY category_name, revenue_rank;


-- Q27. Split customers into 4 equal spending groups (quartiles)
-- Quartile 1 = top spenders, quartile 4 = lowest spenders
SELECT
    customer_name,
    total_spent,
    NTILE(4) OVER (ORDER BY total_spent DESC) AS spending_quartile
FROM (
    SELECT
        CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
        ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS total_spent
    FROM customers cu
    JOIN orders      o  ON cu.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id     = oi.order_id
    WHERE o.status != 'Cancelled'
    GROUP BY cu.customer_id, customer_name
) AS spending
ORDER BY spending_quartile, total_spent DESC;


-- Q28. Running total of revenue across all delivered orders over time
SELECT
    order_id,
    order_date,
    order_revenue,
    ROUND(
        SUM(order_revenue) OVER (ORDER BY order_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    2) AS running_total
FROM vw_order_summary
WHERE status = 'Delivered'
ORDER BY order_date;


-- Q29. 3-order rolling average to smooth out revenue spikes
SELECT
    order_id,
    order_date,
    order_revenue,
    ROUND(AVG(order_revenue) OVER (
        ORDER BY order_date
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ), 2) AS rolling_3_avg
FROM vw_order_summary
WHERE status = 'Delivered'
ORDER BY order_date;


-- Q30. Compare each order's revenue to the one before and after it
-- Useful for spotting sudden revenue jumps or drops
SELECT
    order_id,
    order_date,
    order_revenue,
    LAG(order_revenue,  1) OVER (ORDER BY order_date) AS prev_order_revenue,
    LEAD(order_revenue, 1) OVER (ORDER BY order_date) AS next_order_revenue,
    ROUND(order_revenue - LAG(order_revenue, 1) OVER (ORDER BY order_date), 2) AS revenue_change
FROM vw_order_summary
WHERE status = 'Delivered'
ORDER BY order_date;


-- Q31. Month-over-month revenue change, broken down by region
-- LAG is partitioned so each region compares against its own previous month
WITH monthly_revenue AS (
    SELECT
        region_name,
        DATE_FORMAT(order_date, '%Y-%m') AS order_month,
        ROUND(SUM(order_revenue), 2)     AS monthly_rev
    FROM vw_order_summary
    WHERE status = 'Delivered'
    GROUP BY region_name, order_month
)
SELECT
    region_name,
    order_month,
    monthly_rev,
    LAG(monthly_rev) OVER (PARTITION BY region_name ORDER BY order_month) AS prev_month_rev,
    ROUND(
        monthly_rev - LAG(monthly_rev) OVER (PARTITION BY region_name ORDER BY order_month),
    2) AS mom_change
FROM monthly_revenue
ORDER BY region_name, order_month;


-- Q32. For each customer, find their very first and most recent order
-- We use FIRST_VALUE twice: once sorted oldest-first, once newest-first
SELECT DISTINCT
    customer_name,
    FIRST_VALUE(order_id)   OVER (PARTITION BY customer_id ORDER BY order_date)      AS first_order_id,
    FIRST_VALUE(order_date) OVER (PARTITION BY customer_id ORDER BY order_date)      AS first_order_date,
    FIRST_VALUE(order_id)   OVER (PARTITION BY customer_id ORDER BY order_date DESC) AS last_order_id,
    FIRST_VALUE(order_date) OVER (PARTITION BY customer_id ORDER BY order_date DESC) AS last_order_date
FROM vw_order_summary
ORDER BY customer_name;



-- SECTION 9: CTEs (Common Table Expressions)

-- Q33. Calculate how much each customer has spent, then assign them a tier
-- The CTE handles the math, the outer query handles the labelling
WITH customer_spending AS (
    SELECT
        cu.customer_id,
        CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
        cu.segment,
        ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS total_spent
    FROM customers cu
    JOIN orders      o  ON cu.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id     = oi.order_id
    WHERE o.status != 'Cancelled'
    GROUP BY cu.customer_id, customer_name, cu.segment
)
SELECT
    customer_name,
    segment,
    total_spent,
    CASE
        WHEN total_spent >= 200000 THEN 'Platinum'
        WHEN total_spent >= 100000 THEN 'Gold'
        WHEN total_spent >= 30000  THEN 'Silver'
        ELSE 'Bronze'
    END AS value_tier
FROM customer_spending
ORDER BY total_spent DESC;


-- Q34. What percentage of total revenue does each category contribute?
-- Two CTEs are chained: first we get revenue per category, then the grand total
WITH category_rev AS (
    SELECT
        cat.category_name,
        ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS cat_revenue
    FROM order_items oi
    JOIN products    p   ON oi.product_id = p.product_id
    JOIN categories  cat ON p.category_id = cat.category_id
    JOIN orders      o   ON oi.order_id   = o.order_id
    WHERE o.status != 'Cancelled'
    GROUP BY cat.category_name
),
total_rev AS (
    SELECT SUM(cat_revenue) AS grand_total FROM category_rev
)
SELECT
    cr.category_name,
    cr.cat_revenue,
    ROUND(cr.cat_revenue / tr.grand_total * 100, 2) AS revenue_share_pct
FROM category_rev cr
CROSS JOIN total_rev tr
ORDER BY revenue_share_pct DESC;


-- Q35. Build the full employee hierarchy from top manager down to each staff member
-- The recursive CTE starts at the top (no manager) and works its way down level by level
WITH RECURSIVE org_chart AS (

    -- Start with top-level employees who have no manager above them
    SELECT
        employee_id,
        CONCAT(first_name, ' ', last_name)          AS employee_name,
        job_title,
        manager_id,
        0                                            AS level,
        CAST(CONCAT(first_name, ' ', last_name) AS CHAR(500)) AS hierarchy_path
    FROM employees
    WHERE manager_id IS NULL

    UNION ALL

    -- For each employee found, find who reports to them
    SELECT
        e.employee_id,
        CONCAT(e.first_name, ' ', e.last_name),
        e.job_title,
        e.manager_id,
        oc.level + 1,
        CONCAT(oc.hierarchy_path, ' > ', e.first_name, ' ', e.last_name)
    FROM employees e
    JOIN org_chart oc ON e.manager_id = oc.employee_id
)
SELECT
    REPEAT('    ', level) AS indent,
    employee_name,
    job_title,
    level,
    hierarchy_path
FROM org_chart
ORDER BY hierarchy_path;



-- SECTION 10: Stored Procedures and Functions


DELIMITER $$

-- Procedure 1: Pass in a customer ID and get back all their orders with totals
CREATE PROCEDURE sp_get_customer_orders(IN p_customer_id INT)
BEGIN
    SELECT
        o.order_id,
        o.order_date,
        o.status,
        ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS order_total
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.customer_id = p_customer_id
    GROUP BY o.order_id, o.order_date, o.status
    ORDER BY o.order_date DESC;
END$$


-- Procedure 2: Reduce prices for all active products in a given category
-- Returns how many products were updated via the OUT parameter
CREATE PROCEDURE sp_apply_category_discount(
    IN  p_category_id      INT,
    IN  p_discount_pct     DECIMAL(4,2),
    OUT p_products_updated INT
)
BEGIN
    UPDATE products
    SET unit_price = ROUND(unit_price * (1 - p_discount_pct / 100), 2)
    WHERE category_id = p_category_id
      AND is_active = 1;

    SET p_products_updated = ROW_COUNT();
END$$


-- Function: Give it an order ID, it returns the net revenue for that order
CREATE FUNCTION fn_order_revenue(p_order_id INT)
RETURNS DECIMAL(12,2)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE v_revenue DECIMAL(12,2);

    SELECT ROUND(SUM(quantity * unit_price * (1 - discount_pct)), 2)
    INTO v_revenue
    FROM order_items
    WHERE order_id = p_order_id;

    RETURN COALESCE(v_revenue, 0);
END$$

DELIMITER ;


-- Test the procedure and function with real data
CALL sp_get_customer_orders(2);
SELECT fn_order_revenue(1) AS order_1_revenue;
SELECT fn_order_revenue(2) AS order_2_revenue;



-- SECTION 11: Indexes for Performance


-- Single-column indexes on columns we filter by most often
CREATE INDEX idx_orders_status      ON orders(status);
CREATE INDEX idx_orders_order_date  ON orders(order_date);
CREATE INDEX idx_products_category  ON products(category_id);
CREATE INDEX idx_customers_city     ON customers(city);
CREATE INDEX idx_customers_segment  ON customers(segment);

-- Composite index for queries that filter by both status and date together
CREATE INDEX idx_orders_status_date ON orders(status, order_date);

-- Use EXPLAIN to see if MySQL is actually using the index above
EXPLAIN
SELECT o.order_id, o.order_date, o.status
FROM orders o
WHERE o.status = 'Delivered'
  AND o.order_date >= '2023-01-01';



-- SECTION 12: Update and Delete (DML)

-- After orders are delivered, subtract sold quantities from stock
UPDATE products p
JOIN (
    SELECT product_id, SUM(quantity) AS total_sold
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.order_id
    WHERE o.status = 'Delivered'
    GROUP BY product_id
) AS sales ON p.product_id = sales.product_id
SET p.stock_qty = p.stock_qty - sales.total_sold
WHERE p.stock_qty >= sales.total_sold;


-- Mark any product with no remaining stock as inactive
UPDATE products
SET is_active = 0
WHERE stock_qty = 0;


-- Clean up old cancelled orders 
DELETE FROM orders
WHERE status = 'Cancelled'
  AND order_date < DATE_SUB(NOW(), INTERVAL 1 YEAR);

-- SECTION 13: Capstone Query
-- Putting it all together: CTEs + window functions + CASE WHEN

WITH

-- Step 1: Total up how much each customer has spent and how many orders they made
customer_stats AS (
    SELECT
        cu.customer_id,
        CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
        cu.city,
        cu.segment,
        COUNT(DISTINCT o.order_id)               AS total_orders,
        ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_pct)), 2) AS lifetime_value
    FROM customers cu
    JOIN orders      o  ON cu.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id     = oi.order_id
    WHERE o.status != 'Cancelled'
    GROUP BY cu.customer_id, customer_name, cu.city, cu.segment
),

-- Step 2: Apply rankings and quartiles using window functions
ranked_customers AS (
    SELECT
        *,
        RANK()   OVER (ORDER BY lifetime_value DESC)                          AS overall_rank,
        RANK()   OVER (PARTITION BY city ORDER BY lifetime_value DESC)        AS city_rank,
        NTILE(4) OVER (ORDER BY lifetime_value DESC)                          AS spending_quartile,
        ROUND(lifetime_value / SUM(lifetime_value) OVER () * 100, 2)         AS revenue_share_pct
    FROM customer_stats
)

-- Step 3: Final output with a readable tier label for each customer
SELECT
    overall_rank,
    customer_name,
    city,
    segment,
    total_orders,
    lifetime_value,
    city_rank,
    revenue_share_pct,
    spending_quartile,
    CASE spending_quartile
        WHEN 1 THEN 'Platinum - Top 25%'
        WHEN 2 THEN 'Gold - Upper Mid'
        WHEN 3 THEN 'Silver - Lower Mid'
        WHEN 4 THEN 'Bronze - Bottom 25%'
    END AS customer_tier
FROM ranked_customers
ORDER BY overall_rank;


-- End of project